# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f70980cbb24cd7180b7efd95a8abd338f4dbf1d29aa1a861ef9f14cc7f227421fa2141eaf30ce5788813c11815f7975b2229cc33744cac375c49bea2866c6fd

test:
  secret_key_base: 388d45bb368fcce78a914a438813b1be43b1f04fe6b98fe420dccbedcc03658fecde15f42f403d429946f6ccbcf7b97f5a0582d5b7a61b7f07ba16192d684f96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
